image: buhala/eventzoom-aws:latest
services:
  - mongo


cache:
  paths:
  - node/node_modules/
  - react/node_modules/

stages:
  - test
  - deploy_staging

node-test:
  variables:
    MONGO_URL: 'mongodb://mongo/eventzoom'
  stage: test
  script:
   - cd node/
   - npm i
   - npm run test
   - npm run lint
   - npm run seed

react-test:
  stage: test
  script:
   - cd react/
   - npm i
   - npm test
   - npm run lint


react-deploy:
  only:
    - develop
  stage: deploy_staging
  script:
   - cd react/
   - npm i
   - CI="" npm run build
   - cd build/
   - aws s3 sync ./ s3://eventzoom/



node-deploy:
  only:
    - develop
  stage: deploy_staging
  script:
    - cd node
    - npm i
    - mv .env .env.dev
    - mv .env.serverless .env
    - npx db-migrate db:drop test
    - npm run seed
    - mv .env .env.serverless
    - mv .env.dev .env
    - npm run update-lambda