image: node:8.10.0

cache:
  paths:
  - node/node_modules/
  - react/node_modules/

stages:
  - test

node-test:
  stage: test
  script:
   - cd node/
   - npm i
   - npm test
   - npm run lint

react-test:
  stage: test
  script:
   - cd react/
   - npm i
   - npm test
   - npm run lint
