image: node:10.17.0
services:
  - mongo
variables:
  MONGO_URL: 'mongodb://mongo/eventzoom'

cache:
  paths:
  - node/node_modules/
  - react/node_modules/

stages:
  - test
  - deploy_staging

node-test:
  stage: test
  script:
   - cd node/
   - npm i
   - npm run test
   - npm run lint
   - npm run seed

react-test:
  stage: test
  script:
   - cd react/
   - npm i
   - npm test
   - npm run lint


react-deploy:
  stage: deploy_staging
  script:
   - apt-get update
   - apt-get install python-setuptools -y
   - easy_install pip
   - pip install awscli
   - cd react/
   - npm i
   - CI="" npm run build
   - cd build/
   - aws s3 sync ./ s3://eventzoom/



node-deploy:
  stage: deploy_staging
  cache: {}
  script:
    - cd final-client-project/node
    - npm i
    - mv .env .env.dev
    - mv .env.serverless .env
    - npx db-migrate db:drop test
    - npm run seed
    - mv .env .env.serverless
    - mv .env.dev .env